services:
  sentinelx:
    build: .
    container_name: sentinelx
    ports:
      - "8000:8000"
    environment:
      SENTINELX_ENVIRONMENT: docker
      SENTINELX_DEBUG: "false"
    volumes:
      - sentinelx-data:/app/data
      - sentinelx-auth-log:/shared:ro
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped

  security-target:
    build: ./lab/security-target
    container_name: sentinelx-security-target
    ports:
      - "2222:22"
    volumes:
      - sentinelx-auth-log:/shared
    restart: "no"

volumes:
  sentinelx-data:
  sentinelx-auth-log:
